version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pp3times/backend:v1

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pp3times/frontend:v1
