version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: trdamp/backend-site:v1

  frontend:
    ports:
      - '3000:3000'
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: trdamp/html-static-site:v1
