version: '3'

services:
  backend:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  # client:
  #   build: ./client
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./client:/app
